### ISSUE TITLE
Binary release

### ISSUE THREAD

**Issue by niutech** [jacereda/cosmogfx#2]
Could you provide a binary release, please?

**Comment by jacereda** [comment]
I've uploaded a `demo.com` executable:

https://github.com/jacereda/cosmogfx/releases/download/untagged-03fd90a994c34f017bf2/demo.com

A security vendor marks it as dangerous:

https://www.virustotal.com/gui/file/3fdac69e18c54e7d3280ae4f553eac99dfc61f12e173385bbffc9849fc55fb53/detection

I guess it's just a false positive, since it contains embedded ELF files and that's kind of suspicious.

**Comment by niutech** [comment]
@jacereda https://github.com/jacereda/cosmogfx/releases is empty, could you please upload the demo binary to another hosting?

**Comment by jacereda** [comment]
It was in draft mode, try now.

**Comment by niutech** [comment]
It works, thank you!

![Cosmogfx in Windows 10](https://user-images.githubusercontent.com/384997/192265584-a36e3a85-a177-4e71-a9d5-ccc0d6333b27.png)
